"""Plugin and add-in contract package."""

from __future__ import annotations

from osw.plugins.base import (
    CADImporterPlugin,
    MeshGeneratorPlugin,
    MeshImporterPlugin,
    PluginContractError,
    PostProcessorPlugin,
    PropertyModelPlugin,
    ReportPlugin,
    ScriptImporterPlugin,
    SolverAdapterPlugin,
    WorkbenchPlugin,
)
from osw.plugins.discovery import (
    DuplicatePluginIdError,
    PluginDiscoveryError,
    PluginRegistry,
    discover_entry_point_plugins,
    discover_local_plugins,
    discover_plugins,
)
from osw.plugins.health import (
    InvalidPluginHealthRecord,
    PluginExecutableStatus,
    PluginHealth,
    PluginHealthRecord,
    PluginHealthRow,
    PluginHealthStatus,
    build_plugin_health_record,
    check_manifest_health,
    collect_plugin_health_records,
    plugin_health_records_as_json,
    plugin_health_records_as_text,
)
from osw.plugins.installer import (
    DuplicatePluginInstallError,
    PluginInstallError,
    PluginInstallManager,
    PluginInstallResult,
    PluginValidationResult,
    ZipPathTraversalError,
)
from osw.plugins.manifest import PluginManifest, PluginManifestError, PluginType

__all__ = [
    "CADImporterPlugin",
    "DuplicatePluginIdError",
    "DuplicatePluginInstallError",
    "InvalidPluginHealthRecord",
    "MeshGeneratorPlugin",
    "MeshImporterPlugin",
    "PluginContractError",
    "PluginDiscoveryError",
    "PluginHealth",
    "PluginExecutableStatus",
    "PluginHealthRecord",
    "PluginHealthRow",
    "PluginHealthStatus",
    "PluginInstallError",
    "PluginInstallManager",
    "PluginInstallResult",
    "PluginManifest",
    "PluginManifestError",
    "PluginRegistry",
    "PluginType",
    "PluginValidationResult",
    "PostProcessorPlugin",
    "PropertyModelPlugin",
    "ReportPlugin",
    "ScriptImporterPlugin",
    "SolverAdapterPlugin",
    "WorkbenchPlugin",
    "ZipPathTraversalError",
    "build_plugin_health_record",
    "check_manifest_health",
    "collect_plugin_health_records",
    "discover_entry_point_plugins",
    "discover_local_plugins",
    "discover_plugins",
    "plugin_health_records_as_json",
    "plugin_health_records_as_text",
]
