"""Plugin and add-in contract package."""

from __future__ import annotations

from osw.plugins.base import (
    CADImporterPlugin,
    MeshGeneratorPlugin,
    MeshImporterPlugin,
    PluginContractError,
    PostProcessorPlugin,
    PropertyModelPlugin,
    ReportPlugin,
    ScriptImporterPlugin,
    SolverAdapterPlugin,
    WorkbenchPlugin,
)
from osw.plugins.discovery import (
    DuplicatePluginIdError,
    PluginDiscoveryError,
    PluginDiscoveryRecord,
    PluginDiscoveryResult,
    discover_entry_point_plugins,
    discover_entry_points,
    discover_local_plugin_manifests,
    discover_local_plugins,
    discover_plugin_search_paths,
    discover_plugins,
    load_entry_point_plugin,
)
from osw.plugins.errors import (
    PluginDiagnostic,
    PluginDiagnosticSeverity,
    PluginError,
    PluginValidationError,
)
from osw.plugins.examples import (
    builtin_meshio_plugin_manifest,
    builtin_mscript_preview_plugin_manifest,
    builtin_plugin_manifests,
)
from osw.plugins.health import (
    InvalidPluginHealthRecord,
    PluginExecutableStatus,
    PluginHealth,
    PluginHealthRecord,
    PluginHealthRow,
    PluginHealthStatus,
    build_plugin_health_record,
    check_manifest_health,
    collect_plugin_health_records,
    plugin_health_records_as_json,
    plugin_health_records_as_text,
)
from osw.plugins.installer import (
    DuplicatePluginInstallError,
    PluginInstallError,
    PluginInstallManager,
    PluginInstallResult,
    PluginValidationResult,
    ZipPathTraversalError,
)
from osw.plugins.manifest import (
    PluginDomain,
    PluginManifest,
    PluginManifestError,
    PluginType,
    validate_manifest_data,
)
from osw.plugins.registry import PluginRegistry, PluginRegistryEntry
from osw.plugins.state import PluginStateStore

__all__ = [
    "CADImporterPlugin",
    "DuplicatePluginIdError",
    "DuplicatePluginInstallError",
    "InvalidPluginHealthRecord",
    "MeshGeneratorPlugin",
    "MeshImporterPlugin",
    "PluginContractError",
    "PluginDiagnostic",
    "PluginDiagnosticSeverity",
    "PluginDiscoveryError",
    "PluginDiscoveryRecord",
    "PluginDiscoveryResult",
    "PluginDomain",
    "PluginError",
    "PluginHealth",
    "PluginExecutableStatus",
    "PluginHealthRecord",
    "PluginHealthRow",
    "PluginHealthStatus",
    "PluginInstallError",
    "PluginInstallManager",
    "PluginInstallResult",
    "PluginManifest",
    "PluginManifestError",
    "PluginRegistry",
    "PluginRegistryEntry",
    "PluginStateStore",
    "PluginType",
    "PluginValidationError",
    "PluginValidationResult",
    "PostProcessorPlugin",
    "PropertyModelPlugin",
    "ReportPlugin",
    "ScriptImporterPlugin",
    "SolverAdapterPlugin",
    "WorkbenchPlugin",
    "ZipPathTraversalError",
    "build_plugin_health_record",
    "builtin_meshio_plugin_manifest",
    "builtin_mscript_preview_plugin_manifest",
    "builtin_plugin_manifests",
    "check_manifest_health",
    "collect_plugin_health_records",
    "discover_entry_points",
    "discover_entry_point_plugins",
    "discover_local_plugins",
    "discover_local_plugin_manifests",
    "discover_plugin_search_paths",
    "discover_plugins",
    "load_entry_point_plugin",
    "plugin_health_records_as_json",
    "plugin_health_records_as_text",
    "validate_manifest_data",
]
