"""OpenFOAM bounded template helpers for OSW v0.1."""

from __future__ import annotations

from .adapter import OpenFoamCavityTemplateAdapter, OpenFoamDuctTemplateAdapter
from .case_generator import (
    OSW_OPENFOAM_TEMPLATE_FOUNDATION_V12_PHYSICAL_PROPERTIES,
    OSW_OPENFOAM_TEMPLATE_LEGACY_TRANSPORT_PROPERTIES,
    OSW_OPENFOAM_TEMPLATE_VARIANT_UNSUPPORTED,
    OpenFoamBoundaryConfig,
    OpenFoamCaseGenerator,
    OpenFoamCaseTemplateError,
    OpenFoamCavityConfig,
    OpenFoamDuctCaseGenerator,
    OpenFoamDuctConfig,
    OpenFoamDuctPatchConfig,
    OpenFoamGeneratedCase,
    default_cavity_request,
    default_duct_request,
    generate_cavity_case,
    generate_duct_case,
    generate_openfoam_case,
    layout_diagnostic_code,
    property_file_for_layout,
    resolve_property_file_layout,
    validate_case_request,
    write_openfoam_case,
)
from .model import (
    OpenFOAMBoundaryPatch,
    OpenFOAMBoundaryType,
    OpenFOAMCaseRequest,
    OpenFOAMCaseResult,
    OpenFOAMControlSettings,
    OpenFOAMPropertyFileLayout,
    OpenFOAMResidualSeries,
    OpenFOAMResidualSummary,
    OpenFOAMRunPolicy,
    OpenFOAMRunRequest,
    OpenFOAMRunResult,
    OpenFOAMRunStatus,
    OpenFOAMSolverKind,
    OpenFOAMTemplateKind,
    OpenFOAMTransportProperties,
)
from .residual_parser import (
    parse_openfoam_case_logs,
    parse_openfoam_log,
    parse_openfoam_residuals_from_text,
)
from .residuals import (
    OpenFoamResidualParser,
    OpenFoamResidualPoint,
    OpenFoamResidualSeries,
)
from .results import openfoam_residuals_to_result_dataset, result_dataset_from_openfoam_run
from .runner import (
    OpenFOAMRunner,
    blockmesh_available,
    find_openfoam_executable,
    openfoam_solver_available,
)

__all__ = [
    "OSW_OPENFOAM_TEMPLATE_FOUNDATION_V12_PHYSICAL_PROPERTIES",
    "OSW_OPENFOAM_TEMPLATE_LEGACY_TRANSPORT_PROPERTIES",
    "OSW_OPENFOAM_TEMPLATE_VARIANT_UNSUPPORTED",
    "OpenFoamBoundaryConfig",
    "OpenFoamCaseGenerator",
    "OpenFoamCaseTemplateError",
    "OpenFoamCavityConfig",
    "OpenFoamCavityTemplateAdapter",
    "OpenFoamDuctCaseGenerator",
    "OpenFoamDuctConfig",
    "OpenFoamDuctPatchConfig",
    "OpenFoamDuctTemplateAdapter",
    "OpenFoamGeneratedCase",
    "OpenFOAMBoundaryPatch",
    "OpenFOAMBoundaryType",
    "OpenFOAMCaseRequest",
    "OpenFOAMCaseResult",
    "OpenFOAMControlSettings",
    "OpenFOAMPropertyFileLayout",
    "OpenFOAMResidualSeries",
    "OpenFOAMResidualSummary",
    "OpenFOAMRunPolicy",
    "OpenFOAMRunRequest",
    "OpenFOAMRunResult",
    "OpenFOAMRunStatus",
    "OpenFOAMRunner",
    "OpenFOAMSolverKind",
    "OpenFOAMTemplateKind",
    "OpenFOAMTransportProperties",
    "OpenFoamResidualParser",
    "OpenFoamResidualPoint",
    "OpenFoamResidualSeries",
    "blockmesh_available",
    "default_cavity_request",
    "default_duct_request",
    "find_openfoam_executable",
    "generate_cavity_case",
    "generate_duct_case",
    "generate_openfoam_case",
    "layout_diagnostic_code",
    "openfoam_residuals_to_result_dataset",
    "openfoam_solver_available",
    "parse_openfoam_case_logs",
    "parse_openfoam_log",
    "parse_openfoam_residuals_from_text",
    "property_file_for_layout",
    "resolve_property_file_layout",
    "result_dataset_from_openfoam_run",
    "validate_case_request",
    "write_openfoam_case",
]
