"""CalculiX linear static input deck generation."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from osw.core.materials import Material
from osw.core.validation import ValidationReport
from osw.mesh.mesh_model import MeshCellBlock, MeshData

from .model import (
    CalculiXBoundary,
    CalculiXDeckResult,
    CalculiXDeckStatus,
    CalculiXElement,
    CalculiXElementSet,
    CalculiXInputDeck,
    CalculiXMaterial,
    CalculiXNode,
    CalculiXStep,
    CalculiXSurfaceSet,
)
from .model import (
    CalculiXLoad as CalculiXModelLoad,
)
from .model import (
    CalculiXNodeSet as CalculiXModelNodeSet,
)
from .validation import SUPPORTED_CELL_TYPES, validate_calculix_case

LoadKind = Literal["force", "pressure"]


class CalculixInputDeckError(ValueError):
    """Raised when a CalculiX input deck cannot be generated safely."""


@dataclass(frozen=True)
class CalculixNodeSet:
    """Named one-based CalculiX node set."""

    name: str
    node_ids: tuple[int, ...]

    def __init__(self, name: str, node_ids: tuple[int, ...]) -> None:
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "node_ids", tuple(int(node_id) for node_id in node_ids))


@dataclass(frozen=True)
class CalculixSurface:
    """Named CalculiX element surface using element id and face label pairs."""

    name: str
    element_faces: tuple[tuple[int, str], ...]

    def __init__(self, name: str, element_faces: tuple[tuple[int, str], ...]) -> None:
        normalized = tuple((int(element_id), str(face)) for element_id, face in element_faces)
        object.__setattr__(self, "name", name)
        object.__setattr__(self, "element_faces", normalized)


@dataclass(frozen=True)
class CalculixBoundaryCondition:
    """Boundary condition supported by the v0.1 linear static deck generator."""

    name: str
    node_set: str
    dof_start: int = 1
    dof_end: int = 3
    value: float = 0.0
    kind: str = "fixed"

    @classmethod
    def fixed(
        cls,
        *,
        name: str,
        node_set: str,
        dofs: tuple[int, int] = (1, 3),
        value: float = 0.0,
    ) -> CalculixBoundaryCondition:
        return cls(
            name=name,
            node_set=node_set,
            dof_start=dofs[0],
            dof_end=dofs[1],
            value=value,
            kind="fixed",
        )


@dataclass(frozen=True)
class CalculixLoad:
    """Linear static force or pressure load."""

    name: str
    kind: LoadKind
    value: float
    node_set: str | None = None
    dof: int | None = None
    surface: str | None = None

    @classmethod
    def force(
        cls,
        *,
        name: str,
        node_set: str,
        dof: int,
        value: float,
    ) -> CalculixLoad:
        return cls(name=name, kind="force", node_set=node_set, dof=dof, value=value)

    @classmethod
    def pressure(cls, *, name: str, surface: str, value: float) -> CalculixLoad:
        return cls(name=name, kind="pressure", surface=surface, value=value)


@dataclass(frozen=True)
class CalculixLinearStaticCase:
    """Prepare-only CalculiX case for v0.1 linear static educational demos."""

    case_id: str
    mesh: MeshData
    material: Material | None
    node_sets: tuple[CalculixNodeSet, ...] = field(default_factory=tuple)
    surfaces: tuple[CalculixSurface, ...] = field(default_factory=tuple)
    boundary_conditions: tuple[CalculixBoundaryCondition, ...] = field(default_factory=tuple)
    loads: tuple[CalculixLoad, ...] = field(default_factory=tuple)
    step_name: str = "linear_static"


class CalculixInputDeckGenerator:
    """Render a deterministic CalculiX `.inp` deck without executing CalculiX."""

    def validate(self, case: CalculixLinearStaticCase) -> ValidationReport:
        return validate_calculix_case(case)

    def generate(self, case: CalculixLinearStaticCase) -> str:
        report = self.validate(case)
        if report.has_errors:
            raise CalculixInputDeckError(report.friendly_summary())

        if case.material is None or case.material.elastic is None:
            raise CalculixInputDeckError("CalculiX material validation did not run.")

        lines: list[str] = [
            "*HEADING",
            f"OSW CalculiX linear static deck: {case.case_id}",
            "** Generated by OpenSolver Workbench",
            "Scope: v0.1 linear static only",
            "** Unit assumptions: SI-compatible project values are expected.",
            "*NODE",
        ]
        lines.extend(_node_lines(case.mesh))
        lines.extend(_element_lines(case.mesh))
        lines.extend(_set_lines("ELSET", "EALL", tuple(range(1, _element_count(case.mesh) + 1))))
        lines.extend(_set_lines("NSET", "NALL", tuple(range(1, len(case.mesh.points) + 1))))
        for node_set in case.node_sets:
            lines.extend(_set_lines("NSET", node_set.name, node_set.node_ids))
        lines.extend(_surface_lines(case.surfaces))
        lines.extend(_material_lines(case.material))
        lines.append(f"*SOLID SECTION, ELSET=EALL, MATERIAL={case.material.material_id}")
        lines.extend(
            [
                f"*STEP, NAME={case.step_name}",
                "*STATIC",
            ]
        )
        lines.extend(_boundary_lines(case.boundary_conditions))
        lines.extend(_load_lines(case.loads))
        lines.extend(
            [
                "*NODE PRINT, NSET=NALL",
                "U",
                "*EL PRINT, ELSET=EALL",
                "S",
                "*END STEP",
            ]
        )
        return "\n".join(lines) + "\n"


def generate_calculix_input_deck(case: CalculixLinearStaticCase) -> str:
    return CalculixInputDeckGenerator().generate(case)


def case_to_input_deck(case: CalculixLinearStaticCase) -> CalculiXInputDeck:
    """Convert a legacy prepare-only case into the report-friendly deck model."""

    diagnostics = _validation_diagnostics(CalculixInputDeckGenerator().validate(case))
    nodes = tuple(
        CalculiXNode(index, coordinates)
        for index, coordinates in enumerate(case.mesh.points, start=1)
    )
    elements: list[CalculiXElement] = []
    element_id = 1
    for block in case.mesh.cells:
        element_type = SUPPORTED_CELL_TYPES.get(block.cell_type, "UNKNOWN")
        for connectivity in block.data:
            elements.append(
                CalculiXElement(
                    element_id=element_id,
                    element_type=element_type,
                    node_ids=tuple(index + 1 for index in connectivity),
                    element_set="EALL",
                    metadata={"source_cell_type": block.cell_type},
                )
            )
            element_id += 1

    materials = ()
    if case.material is not None and case.material.elastic is not None:
        materials = (_material_to_model(case.material),)

    return CalculiXInputDeck(
        heading=f"OSW CalculiX linear static deck: {case.case_id}",
        nodes=nodes,
        elements=tuple(elements),
        materials=materials,
        node_sets=tuple(
            CalculiXModelNodeSet(item.name, item.node_ids)
            for item in case.node_sets
        ),
        element_sets=(
            CalculiXElementSet("EALL", tuple(range(1, len(elements) + 1)), role="domain"),
        ),
        surface_sets=tuple(
            CalculiXSurfaceSet(item.name, item.element_faces) for item in case.surfaces
        ),
        boundaries=tuple(
            CalculiXBoundary(
                name=item.name,
                set_name=item.node_set,
                dof_start=item.dof_start,
                dof_end=item.dof_end,
                value=item.value,
                metadata={"kind": item.kind},
            )
            for item in case.boundary_conditions
        ),
        loads=tuple(_load_to_model(item) for item in case.loads),
        steps=(CalculiXStep(case.step_name),),
        diagnostics=diagnostics,
        metadata={"case_id": case.case_id, "generator": "osw.calculix"},
    )


def generate_input_deck_text(deck: CalculiXInputDeck) -> str:
    """Render a deterministic `.inp` text from a typed deck model."""

    material = deck.materials[0] if deck.materials else None
    material_name = material.name if material is not None else "UNASSIGNED"
    lines = [
        "*HEADING",
        deck.heading,
        "** Generated by OpenSolver Workbench",
        "Scope: v0.1 linear static only",
        "** Unit assumptions: SI-compatible project values are expected.",
        "*NODE",
    ]
    lines.extend(
        f"{node.node_id}, {_format_float(node.coordinates[0])}, "
        f"{_format_float(node.coordinates[1])}, {_format_float(node.coordinates[2])}"
        for node in deck.nodes
    )
    lines.extend(_model_element_lines(deck.elements))
    for element_set in deck.element_sets:
        lines.extend(_set_lines("ELSET", element_set.name, element_set.element_ids))
    lines.extend(_set_lines("NSET", "NALL", tuple(node.node_id for node in deck.nodes)))
    for node_set in deck.node_sets:
        lines.extend(_set_lines("NSET", node_set.name, node_set.node_ids))
    for surface in deck.surface_sets:
        lines.append(f"*SURFACE, NAME={surface.name}, TYPE=ELEMENT")
        lines.extend(f"{element_id}, {face}" for element_id, face in surface.element_faces)
    if material is not None:
        lines.extend(_model_material_lines(material))
    lines.append(f"*SOLID SECTION, ELSET=EALL, MATERIAL={material_name}")
    step = deck.steps[0] if deck.steps else CalculiXStep("linear_static")
    lines.extend([f"*STEP, NAME={step.name}", "*STATIC"])
    if deck.boundaries:
        lines.append("*BOUNDARY")
        lines.extend(
            (
                f"{item.set_name}, {item.dof_start}, {item.dof_end}, "
                f"{_format_float(item.value)}"
            )
            for item in deck.boundaries
        )
    force_lines = _model_force_load_lines(deck.loads)
    pressure_lines = _model_pressure_load_lines(deck.loads)
    if force_lines:
        lines.append("*CLOAD")
        lines.extend(force_lines)
    if pressure_lines:
        lines.append("*DLOAD")
        lines.extend(pressure_lines)
    lines.extend(
        [
            "*NODE PRINT, NSET=NALL",
            "U",
            "*EL PRINT, ELSET=EALL",
            "S",
            "*END STEP",
        ]
    )
    return "\n".join(lines) + "\n"


def write_input_deck(deck_or_text: CalculiXInputDeck | str, path: str | Path) -> Path:
    """Write deterministic deck text without running CalculiX."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = (
        deck_or_text
        if isinstance(deck_or_text, str)
        else generate_input_deck_text(deck_or_text)
    )
    target.write_text(text, encoding="utf-8")
    return target


def deck_result_from_case(
    case: CalculixLinearStaticCase,
    *,
    output_path: str | Path | None = None,
    source_project_name: str = "",
) -> CalculiXDeckResult:
    """Build a structured deck result from a validated legacy case."""

    generator = CalculixInputDeckGenerator()
    report = generator.validate(case)
    diagnostics = _validation_diagnostics(report)
    if report.has_errors:
        return CalculiXDeckResult(
            status=CalculiXDeckStatus.ERROR.value,
            deck=None,
            input_text="",
            output_path=Path(output_path) if output_path else None,
            diagnostics=diagnostics,
            source_project_name=source_project_name,
        )
    deck = case_to_input_deck(case)
    input_text = generator.generate(case)
    status = (
        CalculiXDeckStatus.WARNING.value
        if report.has_warnings
        else CalculiXDeckStatus.OK.value
    )
    return CalculiXDeckResult(
        status=status,
        deck=deck,
        input_text=input_text,
        output_path=Path(output_path) if output_path else None,
        diagnostics=diagnostics,
        source_project_name=source_project_name,
    )


def _node_lines(mesh: MeshData) -> list[str]:
    return [
        f"{index}, {_format_float(x)}, {_format_float(y)}, {_format_float(z)}"
        for index, (x, y, z) in enumerate(mesh.points, start=1)
    ]


def _element_lines(mesh: MeshData) -> list[str]:
    lines: list[str] = []
    element_id = 1
    for block in mesh.cells:
        element_type = _calculix_element_type(block)
        lines.append(f"*ELEMENT, TYPE={element_type}, ELSET=EALL")
        for connectivity in block.data:
            node_ids = [str(index + 1) for index in connectivity]
            lines.append(f"{element_id}, {', '.join(node_ids)}")
            element_id += 1
    return lines


def _model_element_lines(elements: tuple[CalculiXElement, ...]) -> list[str]:
    lines: list[str] = []
    current_type = ""
    for element in elements:
        if element.element_type != current_type:
            current_type = element.element_type
            lines.append(f"*ELEMENT, TYPE={current_type}, ELSET={element.element_set}")
        node_ids = ", ".join(str(index) for index in element.node_ids)
        lines.append(f"{element.element_id}, {node_ids}")
    return lines


def _calculix_element_type(block: MeshCellBlock) -> str:
    try:
        return SUPPORTED_CELL_TYPES[block.cell_type]
    except KeyError as exc:
        msg = f"Unsupported CalculiX element cell type: {block.cell_type}"
        raise CalculixInputDeckError(msg) from exc


def _element_count(mesh: MeshData) -> int:
    return sum(block.count for block in mesh.cells)


def _set_lines(kind: str, name: str, ids: tuple[int, ...]) -> list[str]:
    lines = [f"*{kind}, {kind}={name}"]
    lines.extend(_chunked_ids(ids))
    return lines


def _chunked_ids(ids: tuple[int, ...], *, width: int = 16) -> list[str]:
    if not ids:
        return [""]
    return [
        ", ".join(str(item) for item in ids[index : index + width])
        for index in range(0, len(ids), width)
    ]


def _surface_lines(surfaces: tuple[CalculixSurface, ...]) -> list[str]:
    lines: list[str] = []
    for surface in surfaces:
        lines.append(f"*SURFACE, NAME={surface.name}, TYPE=ELEMENT")
        lines.extend(f"{element_id}, {face}" for element_id, face in surface.element_faces)
    return lines


def _material_lines(material: Material) -> list[str]:
    if material.elastic is None:
        raise CalculixInputDeckError("Material must include isotropic elastic fields.")

    lines = [
        f"*MATERIAL, NAME={material.material_id}",
        "*ELASTIC",
        (
            f"{_format_float(material.elastic.young_modulus.value)}, "
            f"{_format_float(material.elastic.poisson_ratio)}"
        ),
    ]
    if material.density is not None:
        lines.extend(["*DENSITY", _format_float(material.density.value)])
    return lines


def _material_to_model(material: Material) -> CalculiXMaterial:
    if material.elastic is None:
        raise CalculixInputDeckError("Material must include isotropic elastic fields.")
    return CalculiXMaterial(
        name=material.material_id,
        elastic_modulus=material.elastic.young_modulus.value,
        poisson_ratio=material.elastic.poisson_ratio,
        density=material.density.value if material.density is not None else None,
        units="SI",
        source_material_id=material.material_id,
        metadata={
            "display_name": material.name,
            "young_modulus_unit": material.elastic.young_modulus.unit,
            "density_unit": material.density.unit if material.density is not None else "",
        },
    )


def _model_material_lines(material: CalculiXMaterial) -> list[str]:
    lines = [
        f"*MATERIAL, NAME={material.name}",
        "*ELASTIC",
        f"{_format_float(material.elastic_modulus)}, {_format_float(material.poisson_ratio)}",
    ]
    if material.density is not None:
        lines.extend(["*DENSITY", _format_float(material.density)])
    return lines


def _boundary_lines(boundary_conditions: tuple[CalculixBoundaryCondition, ...]) -> list[str]:
    if not boundary_conditions:
        return []
    lines = ["*BOUNDARY"]
    lines.extend(
        (
            f"{item.node_set}, {item.dof_start}, {item.dof_end}, "
            f"{_format_float(item.value)}"
        )
        for item in boundary_conditions
    )
    return lines


def _load_lines(loads: tuple[CalculixLoad, ...]) -> list[str]:
    lines: list[str] = []
    force_loads = [load for load in loads if load.kind == "force"]
    pressure_loads = [load for load in loads if load.kind == "pressure"]
    if force_loads:
        lines.append("*CLOAD")
        for load in force_loads:
            lines.append(f"{load.node_set}, {load.dof}, {_format_float(load.value)}")
    if pressure_loads:
        lines.append("*DLOAD")
        for load in pressure_loads:
            lines.append(f"{load.surface}, P, {_format_float(load.value)}")
    return lines


def _load_to_model(load: CalculixLoad) -> CalculiXModelLoad:
    if load.kind == "force":
        components = [0.0, 0.0, 0.0]
        if load.dof is not None and 1 <= load.dof <= 3:
            components[load.dof - 1] = load.value
        return CalculiXModelLoad(
            name=load.name,
            load_type="force",
            target_set=load.node_set or "",
            components=tuple(components),
        )
    return CalculiXModelLoad(
        name=load.name,
        load_type="pressure",
        target_set=load.surface or "",
        magnitude=load.value,
    )


def _model_force_load_lines(loads: tuple[CalculiXModelLoad, ...]) -> list[str]:
    lines: list[str] = []
    for load in loads:
        if load.load_type != "force" or load.components is None:
            continue
        for index, value in enumerate(load.components, start=1):
            if value:
                lines.append(f"{load.target_set}, {index}, {_format_float(value)}")
    return lines


def _model_pressure_load_lines(loads: tuple[CalculiXModelLoad, ...]) -> list[str]:
    lines: list[str] = []
    for load in loads:
        if load.load_type == "pressure" and load.magnitude is not None:
            lines.append(f"{load.target_set}, P, {_format_float(load.magnitude)}")
    return lines


def _validation_diagnostics(report: ValidationReport) -> tuple[dict[str, str], ...]:
    return tuple(
        {
            "severity": message.severity,
            "path": message.path,
            "message": message.message,
        }
        for message in report.messages
    )


def _format_float(value: float) -> str:
    return f"{float(value):.12g}"
