"""Core project, unit, material, and dataset contracts."""

from __future__ import annotations

from osw.core.boundary_curve import (
    BoundaryCurve,
    BoundaryCurveError,
    BoundaryCurveKind,
    BoundaryCurveSource,
    BoundaryCurveSourceTrace,
    CurveAxis,
    CurveInterpolation,
    boundary_curve_from_xy,
    export_boundary_curve_csv,
    load_boundary_curve_json,
    make_source_trace,
    save_boundary_curve_json,
)
from osw.core.demo_project import create_heatsink_flow_demo_project
from osw.core.diagnostics import (
    DiagnosticCode,
    DiagnosticMessage,
    DiagnosticReport,
    DiagnosticSeverity,
)
from osw.core.executables import ExecutableLookup, ExecutablePathRegistry, ExecutableResolution
from osw.core.materials import (
    FluidProperties,
    IsotropicElastic,
    IsotropicElasticProperties,
    Material,
    MaterialDB,
    MaterialLibrary,
    ThermalProperties,
    builtin_materials,
)
from osw.core.project_io import (
    load_project_json,
    load_project_yaml,
    save_project,
    save_project_json,
    save_project_yaml,
)
from osw.core.project_schema import (
    BoundaryCondition,
    GeometryRef,
    MeshRef,
    PhysicsSetup,
    PluginRef,
    Project,
    ProjectMetadata,
    ProjectWarning,
    ReportConfig,
    ResultRef,
    ScriptRef,
    SolverConfig,
    load_project,
)
from osw.core.run_manager import RunManager
from osw.core.selection import (
    BoundaryTargetRef,
    EntityKind,
    NamedSelection,
    SelectionMode,
    SelectionState,
    SelectionTargetRef,
)
from osw.core.units import Quantity, UnitSystem
from osw.core.validation import (
    ProjectSchemaError,
    ValidationMessage,
    ValidationReport,
    ValidationSeverity,
    validate_boundaries,
    validate_materials,
    validate_mesh_sanity,
    validate_project,
    validate_project_sanity,
    validate_solver_config,
    validate_units,
)

__all__ = [
    "BoundaryCondition",
    "BoundaryCurve",
    "BoundaryCurveError",
    "BoundaryCurveKind",
    "BoundaryCurveSource",
    "BoundaryCurveSourceTrace",
    "BoundaryTargetRef",
    "CurveAxis",
    "CurveInterpolation",
    "EntityKind",
    "DiagnosticMessage",
    "DiagnosticReport",
    "DiagnosticSeverity",
    "DiagnosticCode",
    "ExecutableLookup",
    "ExecutablePathRegistry",
    "ExecutableResolution",
    "FluidProperties",
    "GeometryRef",
    "IsotropicElastic",
    "IsotropicElasticProperties",
    "Material",
    "MaterialDB",
    "MaterialLibrary",
    "MeshRef",
    "PhysicsSetup",
    "PluginRef",
    "Project",
    "ProjectMetadata",
    "ProjectSchemaError",
    "ProjectWarning",
    "Quantity",
    "ReportConfig",
    "ResultRef",
    "RunManager",
    "ScriptRef",
    "SelectionMode",
    "SelectionState",
    "SelectionTargetRef",
    "NamedSelection",
    "SolverConfig",
    "ThermalProperties",
    "UnitSystem",
    "ValidationMessage",
    "ValidationReport",
    "ValidationSeverity",
    "boundary_curve_from_xy",
    "builtin_materials",
    "create_heatsink_flow_demo_project",
    "export_boundary_curve_csv",
    "load_boundary_curve_json",
    "load_project",
    "load_project_json",
    "load_project_yaml",
    "make_source_trace",
    "save_boundary_curve_json",
    "save_project",
    "save_project_json",
    "save_project_yaml",
    "validate_boundaries",
    "validate_materials",
    "validate_mesh_sanity",
    "validate_project",
    "validate_project_sanity",
    "validate_solver_config",
    "validate_units",
]
